name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Copy .env.testing
        run: cp .env.testing .env

      - name: Set up Laravel Environment
        run: |
          php artisan config:cache
          php artisan key:generate --env=testing
          php artisan migrate:fresh --seed --env=testing
        env:
          APP_ENV: testing
          DB_CONNECTION: sqlite
          DB_DATABASE: ':memory:'

      - name: Start Laravel Server
        run: php artisan serve --host=0.0.0.0 --port=8000 &
        env:
          APP_ENV: testing
          DB_CONNECTION: sqlite
          DB_DATABASE: ':memory:'

      - name: Wait for Laravel to Start
        run: sleep 5

      - name: Run Cypress Tests
        run: npx cypress run
        env:
          CYPRESS_baseUrl: http://localhost:8000
